spring:
  application:
    name: sm-spring-examples
  cloud:
    credentials:
      aws:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
  storage:
    aws-s3:
      enabled: true
      region: ${AWS_REGION:sa-east-1}